AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Flatini backend stack

Parameters:
  LambdaRole:
    Type: String
    Description: The role which the lambda executes

Globals:
  Function:
    Timeout: 50
    Environment:
      Variables:
        ENVIRONMENT: PROD

Resources:

  Database:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "flatini-blob-db"

  FlatiniHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "https://localhost:3000"
          - "http://localhost:3000"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - PATCH

  FlatiniFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 1024
      Role: !Ref LambdaRole
      CodeUri: ./
      Handler: src/app.lambda_handler
      Runtime: python3.9
      Events:
        GetGroupById:
          Type: HttpApi
          Properties:
            Path: /groups/{group_id}
            Method: get
            ApiId: !Ref FlatiniHttpApi
        CreateGroup:
          Type: HttpApi
          Properties:
            Path: /groups
            Method: post
            ApiId: !Ref FlatiniHttpApi
        CreateFlat:
          Type: HttpApi
          Properties:
            Path: /groups/{group_id}/flats
            Method: post
            ApiId: !Ref FlatiniHttpApi
        DeleteFlat:
          Type: HttpApi
          Properties:
            Path: /groups/{group_id}/flats/{flat_id}
            Method: delete
            ApiId: !Ref FlatiniHttpApi

Outputs:
  FlatiniBaseUrl:
    Description: "Base URL for Flatini API"
    Value: !Sub "https://${FlatiniHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"