UPSERT_GROUP_REQUEST = "upsert_group_request"
USER_GROUPS = "user_groups"
GROUP = "group"
USER_BELONGS_TO_AT_LEAST_ONE_GROUP = "user_belongs_to_at_least_one_group"
GROUP_ID = "group_id"
FLAT_ID = "flat_id"
